name: 'LHCI Slack Webhook'
description: 'Send to slack webhook a summary of LHCI results'

inputs:
  slack_webhook:
    description: 'Slack Webhook'
    required: true

  manifest:  # id of input
    description: 'LHCI Manifest'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
